project:
  type: book
  output-dir: docs

book:
  title: "Nanopore amplicon data analysis"
  author: "Luc van Zon"
  search: TRUE
  date: "04/23/2025"
  chapters:
    - index.qmd
    - chapters/NAAM-02-preparation.qmd
    - chapters/NAAM-03-quality_control.qmd
    - chapters/NAAM-04-generate_consensus.qmd
    - chapters/NAAM-05-compare_sequences.qmd
    - chapters/NAAM-06-sars_cov_2.qmd
    - chapters/NAAM-07-nanopore_hpc.qmd

toc: true
number-sections: true
number-depth: 3

format:
  html:
    theme:
      light: flatly
      dark: darkly