channels:
  - conda-forge
  - bioconda
dependencies:
  # Core
  - conda-forge::python=3.10

  # Critical pin, downgrade Snakemake version to ensure compatibility with pangolin
  - bioconda::snakemake=7.32.4
  - bioconda::pangolin

  # Other tools
  - bioconda::samtools
  - conda-forge::pandas
  - bioconda::vcftools
  - bioconda::minimap2
  - bioconda::gofasta
  - bioconda::fastp
  - bioconda::seqkit
  - conda-forge::biopython
  - bioconda::pysam
  - bioconda::nextclade

  # R packages
  - conda-forge::r-plotly 
  - conda-forge::r-dplyr
  - conda-forge::r-tidyr
  - conda-forge::r-stringr
  - conda-forge::r-ggplot2
  - conda-forge::r-scales
  - conda-forge::r-seqinr
  - conda-forge::r-argparse
name: naam
